# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Travel Heat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Travel Heat
  pod 'Firebase/Analytics'
  pod 'Firebase/Database' 

  target 'Travel HeatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Travel HeatUITests' do
    # Pods for testing
  end

end
